### ISSUE TITLE
No module named server

### ISSUE THREAD

**Issue by jbeezley** [DigitalSlideArchive/large_image#104]
I had to remake my virtual environment after updating python.  Now I'm getting an error starting girder:
```python
Running in mode: development
Connected to MongoDB: mongodb://localhost:27017/girder
Using memcached for large_image caching
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jbeezley/emory/girder/girder/__main__.py", line 57, in <module>
    main()
  File "/Users/jbeezley/emory/girder/girder/__main__.py", line 50, in main
    server.setup(args.testing)
  File "girder/utility/server.py", line 145, in setup
    root, appconf = configureServer(test, plugins, curConfig)
  File "girder/utility/server.py", line 115, in configureServer
    plugins, curConfig, ignoreMissing=True))
  File "girder/utility/plugin_utilities.py", line 114, in getToposortedPlugins
    allPlugins = findAllPlugins(curConfig)
  File "girder/utility/plugin_utilities.py", line 362, in findAllPlugins
    findEntryPointPlugins(allPlugins)
  File "girder/utility/plugin_utilities.py", line 349, in findEntryPointPlugins
    data = getattr(entry_point.load(), 'config', {})
  File "/Users/jbeezley/emory/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/Users/jbeezley/emory/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named server
```

This led me to this strangeness:
```python
>>> from large_image import server
Using memcached for large_image caching
>>> server.load
<function load at 0x10ee81de8>
>>> from large_image.server import load
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named server
```

Anyone seen this before?  My `sys.path` looks like this:
```
/Users/jbeezley/emory/env/lib/python27.zip
/Users/jbeezley/emory/env/lib/python2.7
/Users/jbeezley/emory/env/lib/python2.7/plat-darwin
/Users/jbeezley/emory/env/lib/python2.7/plat-mac
/Users/jbeezley/emory/env/lib/python2.7/plat-mac/lib-scriptpackages
/Users/jbeezley/emory/env/lib/python2.7/lib-tk
/Users/jbeezley/emory/env/lib/python2.7/lib-old
/Users/jbeezley/emory/env/lib/python2.7/lib-dynload
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/Users/jbeezley/emory/env/lib/python2.7/site-packages
/Users/jbeezley/emory/girder
/Users/jbeezley/emory/girder/plugins/large_image
/Users/jbeezley/emory/girder_worker
```

**Comment by zachmullen** [comment]
Did this happen after upgrading to v2 of girder, or did your girder version stay the same?

**Comment by jbeezley** [comment]
I'm on girder's `1.x-maintenance` branch.

**Comment by zachmullen** [comment]
And you're loading this via entry point?

**Comment by jbeezley** [comment]
Yes, I thought large_image had to be installed that way.   I removed large_image from my sys.path, and it worked.  I guess the answer is that the entry point loading isn't working.

**Comment by jbeezley** [comment]
I'll go ahead and close this.  I believe it is related to an arcane bug in distribute similar to what is pointed out [here](https://github.com/pypa/pip/issues/126).  The gist is that development installs are not currently supported for this plugin.  Regular installs and non-entry point loading does work.
